version: "2"
services:
  jenkins:
    image: e71f6765f222196dd3cd371ac59c06bfba23dfcf:latest
    environment:
      - MONGO_URL=mongodb+srv://luis:developer@notemaster-develop-s1ccj.mongodb.net/test?retryWrites=true
      - MONGO_DATABASE=health-exercise
      - PORT=8080
    user: root
    ports:
      - 8090:8080